name: SonarQube Scan

on:
  push:
    branches: [ main ]

jobs:
  scan:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=my-project \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://localhost:<NodePort> \
            -Dsonar.login=<your-token>
